//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.Course.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CampusEntities : DbContext
    {
        public CampusEntities()
            : base("name=CampusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Class> Classes { get; set; }
        public DbSet<Course> Courses { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<StudentTeach> StudentTeaches { get; set; }
        public DbSet<TeachTimeSheet> TeachTimeSheets { get; set; }
        public DbSet<Teach> Teaches { get; set; }
        public DbSet<Teacher> Teachers { get; set; }
    }
}
