//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.Course.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeWorkPush
    {
        public int ID { get; set; }
        public Nullable<int> TeachTimeSheetId { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public string Notice { get; set; }
        public string HtmlContent { get; set; }
        public string Evaluation { get; set; }
        public Nullable<System.DateTime> DeadLine { get; set; }
        public Nullable<System.DateTime> PushDate { get; set; }
        public string TeachNo { get; set; }
    }
}
