//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.Course.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teach
    {
        public string TeachNo { get; set; }
        public string CourseNo { get; set; }
        public string TeacherNo { get; set; }
    }
}
