//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.Course.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeachTimeSheet
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public double BTime { get; set; }
        public double ETime { get; set; }
        public string Location { get; set; }
        public string TeachNo { get; set; }
    }
}
